### PR TITLE
Fix npm package vulnerabilities. Fixed react warnings.

### PR DESCRIPTION
**Pull request by PeteLevineA**
Updated babel-eslint fixes the following high vulnerability:

>   High            Regular Expression Denial of Service
Package minimatch
  Dependency of   babel-eslint [dev]
  Path            babel-eslint > babel-core > minimatch
  More info       https://nodesecurity.io/advisories/118

Updated react-measure fixes the following react errors:

> ResizeObserver loop limit exceeded
https://github.com/souporserious/react-measure/issues/104

After these fixes via npm install:

> found 0 vulnerabilities

### CODE REVIEW

**Comment by PeteLevineA** [comment]
@bitriddler Can we also merge master back into develop after this PR is cleared? Also a version bump and npm update would be great for any new potential downloads of this package to no longer get npm security warnings. Thanks!

**Comment by kareemaly** [comment]
@PeteLevineA thanks for your pr, I'll check today and will spend some time to bump all versions 👍

**Comment by kareemaly** [comment]
I will merge this into develop and do some checking and update the rest of dependencies

**Comment by kareemaly** [comment]
@PeteLevineA please check https://github.com/bitriddler/react-items-carousel/releases/tag/2.3.0 this should no longer have security warnings (for the moment)

**Comment by PeteLevineA** [comment]
@bitriddler looks good, npm install from clean, npm start and running locally runs fine as well. Thank you! please do an npm publish when you can with 2.3.0 👍

**Pull request merged**
